<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zk</string>
	</array>
	<key>name</key>
	<string>Zettelkasten</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\A---\s*\n</string>
			<key>comment</key>
			<string>This matches a YAML frontmatter block at the beginning of the document.</string>
			<key>contentName</key>
			<string>text.html.markdown.yaml</string>
			<key>end</key>
			<string>(^|\G)---\s*\n</string>
			<key>name</key>
			<string>markup.raw.block.yaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.zk</string>
	<key>uuid</key>
	<string>CD6156B4-73D6-4DB7-907A-66722AF05579</string>
</dict>
</plist>
